#!/bin/bash

set -eu -o pipefail
. /.functions

require_exe java

[ -v EXE_JAR ] || fail "No executable JAR name has been provided"

set_or_default BASE_DIR "/app"
set_or_default DATA_DIR "${BASE_DIR}/data"
set_or_default INIT_DIR "${BASE_DIR}/init"

require_dir_readwrite "${DATA_DIR}"

DATA_DIR="$(/usr/bin/readlink -f "${DATA_DIR}")"

set_or_default MAIN_CONF "application.yaml"
set_or_default CONF "${DATA_DIR}/${MAIN_CONF}"

#
# Update the SSL certificate trusts
#
init_ssl

#
# If our configuration is missing or empty, we render a new one
#
require_file_readable "${CONF}"

# Add the ability to modify the environment
set_or_default ENV_FILE "/.env"

[ -s "${ENV_FILE}" ] && . "${ENV_FILE}"

#
# Make sure the configuration file gets URL-encoded
#
CONF="$(/usr/bin/readlink -f "${CONF}")"
CONF="$(urlencode "${CONF}")"

#
# Execute it!
#
[ ${#} -lt 1 ] && set -- --spring.config.location="file://${CONF}"
execute java -jar "${EXE_JAR}" "${@}"
