#!/bin/bash

set -eu -o pipefail
. /.functions

require_exe cloudconfig

# We use a wrapper script that *should* do the right thing with
# respect to user IDs, groupIds, etc
exec "/usr/local/bin/run-developer" "${CLOUDCONFIG}" "${@}"
