#!/bin/bash
set -eu -o pipefail

say() {
	echo -e "${@}"
}

fail() {
	say "${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

[ -v SSL_DIR ] || SSL_DIR="/.ssl"
acme-init

#
# In case of development mode...
#
add-developer

case "${DEVELOPMENT,,}" in
	true | t | yes | y | on | enabled | enable | en | 1 ) DEVELOPMENT="true" ;;
	* ) DEVELOPMENT="false" ;;
esac

CLOUDCONFIG="$(type -P cloudconfig)" || fail "The cloudconfig executable was not found in the path"

CMD=("${CLOUDCONFIG}" "${@}")

say "Launching as: ${CMD[@]@Q}"

# If development mode is not active, just launch!
${DEVELOPMENT} || exec "${CMD[@]}"

# If development mode is active, we have to resort to some trickery
say "ID prior to development mode: $(id)"
exec /usr/bin/newgrp developer <<-EOF
	echo "ID changed for development mode: $(id)"
	exec "${CMD[@]@Q}"
EOF
